# Generated by Django 5.1.1 on 2024-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Котята', 'verbose_name_plural': 'котята'},
        ),
        migrations.AlterField(
            model_name='porode',
            name='porode_name',
            field=models.CharField(help_text='Укажите породу котенка', max_length=150, verbose_name='Порода котенка'),
        ),
    ]
