# Generated by Django 5.1.1 on 2024-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_cats_options_alter_porode_porode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='cat_name',
            field=models.CharField(help_text='Укажите имя котенка', max_length=150, unique=True, verbose_name='Имя котенка'),
        ),
    ]
